# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one2one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
