# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one2one', '0002_emp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
